FROM python:3.12-slim

WORKDIR /app

# RUN apt-get update && apt-get install -y --no-install-recommends build-essential libpq-dev && apt-get clean && rm -rf /var/lib/apt/lists/*
ENV ENV=test

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["pytest"]
