version: '3.9'

services:
  banpay_db:
    container_name: banpay_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=banpay_user
      - POSTGRES_DB=banpay_db

  banpay-app:
    container_name: banpay-app
    build:
      context: .
      dockerfile: ./Dockerfile.app
    image: banpayapp:latest
    ports:
      - 8000:8000
    env_file:
      - prod.env
    depends_on:
      - banpay_db
    restart: on-failure

  banpay-test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    image: banpayapp_test:latest
    env_file:
      - prod.env
    volumes:
      - ./test_report:/app/test_report
    command: ["pytest", "--html=test_report/report.html"]
    depends_on:
      - banpay-app
      - banpay_db
    restart: on-failure