version: '3.9'

services:
  banpay_db_test:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=banpay_user
      - POSTGRES_DB=banpay_db_test

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    image: banpayapp:latest
    ports:
      - 8000:8000
    env_file:
      - test.env
    environment:
      - ENV=test
    depends_on:
      - banpay_db_test
    restart: on-failure

  pytest:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    image: banpayapp_test:latest
    env_file:
      - test.env
    environment:
      - ENV=test
    volumes:
      - ./tests:/tests
    command: ["pytest"]
    depends_on:
      - banpay_db_test
      - app
    restart: on-failure